import Providers from "@/components/Providers";
import type { Metadata } from "next";
import "@/styles/App.scss"

export const metadata: Metadata = {
  title: "DRAG AND DROP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
